import { getSession } from '../../lib/session'

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end()

  const session = getSession(req)
  if (!session) return res.status(401).json({ error: 'Not logged in' })

  const { rbxmx, gameName, apiKey, userId } = req.body

  if (!apiKey) return res.status(400).json({ error: 'API key required' })
  if (!userId) return res.status(400).json({ error: 'User ID required' })

  try {
    const boundary = '----FormBoundary' + Math.random().toString(36).slice(2)

    const requestJson = JSON.stringify({
      assetType: 'Model',
      displayName: gameName || 'LuauForge Game',
      description: 'Generated by LuauForge — AI Roblox Game Builder',
      creationContext: {
        creator: { userId: String(userId) }
      }
    })

    const body = [
      `--${boundary}`,
      'Content-Disposition: form-data; name="request"',
      'Content-Type: application/json',
      '',
      requestJson,
      `--${boundary}`,
      `Content-Disposition: form-data; name="fileContent"; filename="${gameName || 'game'}.rbxmx"`,
      'Content-Type: application/xml',
      '',
      rbxmx,
      `--${boundary}--`,
    ].join('\r\n')

    const publishRes = await fetch('https://apis.roblox.com/assets/v1/assets', {
      method: 'POST',
      headers: {
        'x-api-key': apiKey,
        'Content-Type': `multipart/form-data; boundary=${boundary}`,
      },
      body,
    })

    const data = await publishRes.json()

    if (!publishRes.ok) {
      console.error('Roblox publish error:', data)
      return res.status(502).json({ error: data.message || 'Publish failed' })
    }

    return res.status(200).json({ assetId: data.assetId || data.id, success: true })
  } catch (err) {
    console.error('Publish error:', err)
    return res.status(500).json({ error: err.message })
  }
}
