import { getSession } from '../../lib/session'

// Build multipart/form-data as a raw Buffer (required by Roblox Open Cloud API)
function buildMultipart(boundary, requestJson, scriptName, scriptCode) {
  const enc = new TextEncoder()

  const parts = [
    enc.encode(
      `--${boundary}\r\n` +
      `Content-Disposition: form-data; name="request"\r\n` +
      `Content-Type: application/json\r\n\r\n` +
      requestJson +
      `\r\n`
    ),
    enc.encode(
      `--${boundary}\r\n` +
      `Content-Disposition: form-data; name="fileContent"; filename="${scriptName}.luau"\r\n` +
      `Content-Type: application/octet-stream\r\n\r\n`
    ),
    enc.encode(scriptCode),
    enc.encode(`\r\n--${boundary}--\r\n`),
  ]

  // Merge all Uint8Arrays into one Buffer
  const totalLength = parts.reduce((sum, p) => sum + p.length, 0)
  const merged = new Uint8Array(totalLength)
  let offset = 0
  for (const part of parts) {
    merged.set(part, offset)
    offset += part.length
  }
  return Buffer.from(merged)
}

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end()

  // Get userId from the session — never trust the client to send it
  const session = getSession(req)
  if (!session) return res.status(401).json({ error: 'Not logged in' })

  const { scripts, gameName, apiKey } = req.body

  if (!apiKey || typeof apiKey !== 'string' || !apiKey.trim()) {
    return res.status(400).json({ error: 'API key required' })
  }
  if (!scripts || !scripts.length) {
    return res.status(400).json({ error: 'No scripts provided' })
  }

  const results = []
  const errors = []

  for (const script of scripts) {
    try {
      const boundary = '----StudsBoundary' + Date.now() + Math.random().toString(36).slice(2)

      const requestJson = JSON.stringify({
        assetType: 'Luau',
        displayName: `${gameName ? gameName + ' - ' : ''}${script.name}`,
        description: script.description || 'Generated by Studs.gg',
        creationContext: {
          creator: { userId: String(session.userId) }, // from session, not body
        },
      })

      const body = buildMultipart(boundary, requestJson, script.name, script.code)

      const publishRes = await fetch('https://apis.roblox.com/assets/v1/assets', {
        method: 'POST',
        headers: {
          'x-api-key': apiKey.trim(),
          'Content-Type': `multipart/form-data; boundary=${boundary}`,
          'Content-Length': String(body.length),
        },
        body,
      })

      let data
      const text = await publishRes.text()
      try { data = JSON.parse(text) } catch { data = { message: text } }

      if (!publishRes.ok) {
        console.error(`Roblox publish error [${script.name}]:`, data)

        // Build a helpful error message based on status
        let message = data.message || data.error || `Failed to publish ${script.name}`
        if (publishRes.status === 401) message = `Invalid API key — generate a new one at create.roblox.com/credentials`
        if (publishRes.status === 403) message = `API key missing Asset:Write permission — edit the key and enable it`
        if (publishRes.status === 429) message = `Rate limited — wait a moment and try again`

        // Don't stop — collect errors and continue with other scripts
        errors.push({ name: script.name, error: message })
        continue
      }

      results.push({
        name: script.name,
        assetId: data.assetId || data.id || null,
      })
    } catch (err) {
      console.error(`Exception publishing ${script.name}:`, err)
      errors.push({ name: script.name, error: err.message })
    }
  }

  // Return partial success if at least one script uploaded
  if (errors.length > 0 && results.length === 0) {
    return res.status(502).json({
      error: errors[0].error,
      errors,
    })
  }

  return res.status(200).json({
    success: true,
    uploaded: results.length,
    failed: errors.length,
    results,
    errors,
  })
}
