import { getSession } from '../../lib/session'

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end()

  const session = getSession(req)
  if (!session) return res.status(401).json({ error: 'Not logged in' })

  const { scripts, gameName, apiKey, userId } = req.body

  if (!apiKey) return res.status(400).json({ error: 'API key required' })
  if (!scripts || !scripts.length) return res.status(400).json({ error: 'No scripts' })

  try {
    const results = []

    for (const script of scripts) {
      const boundary = '----Boundary' + Math.random().toString(36).slice(2)

      const requestJson = JSON.stringify({
        assetType: 'Luau',
        displayName: `${gameName} - ${script.name}`,
        description: script.description || 'Generated by LuauForge',
        creationContext: {
          creator: { userId: String(userId) }
        }
      })

      const body = [
        `--${boundary}`,
        'Content-Disposition: form-data; name="request"',
        'Content-Type: application/json',
        '',
        requestJson,
        `--${boundary}`,
        `Content-Disposition: form-data; name="fileContent"; filename="${script.name}.lua"`,
        'Content-Type: text/plain',
        '',
        script.code,
        `--${boundary}--`,
      ].join('\r\n')

      const publishRes = await fetch('https://apis.roblox.com/assets/v1/assets', {
        method: 'POST',
        headers: {
          'x-api-key': apiKey,
          'Content-Type': `multipart/form-data; boundary=${boundary}`,
        },
        body,
      })

      const data = await publishRes.json()

      if (!publishRes.ok) {
        console.error('Roblox publish error:', data)
        return res.status(502).json({ error: data.message || `Failed to publish ${script.name}` })
      }

      results.push({ name: script.name, assetId: data.assetId || data.id })
    }

    return res.status(200).json({ results, success: true })
  } catch (err) {
    console.error('Publish error:', err)
    return res.status(500).json({ error: err.message })
  }
}
